### ISSUE TITLE
Something missing

### ISSUE THREAD

**Issue by inhydrox** [TheSharks/Tyr#1]
I have been figuring out from 2 days for using lavalink in eris, but finally found this and looks awesome but lacks documentation and a example bot

**Comment by linuswillner** [comment]
The library is still in development and has not been thorougly vetted and prepared for public use. The only current internal implementation of it can be found in [WildBeast/v7](https://github.com/TheSharks/WildBeast/tree/v7). More documentation should be coming in the future.

**Comment by Dougley** [comment]
I've added more inline documentation and published those at https://thesharks.github.io/Tyr, this should be sufficient
